### ISSUE TITLE
IPFS setup sometimes fails

### ISSUE THREAD

**Issue by icidasset** [fission-suite/webnative#129]
<img width="676" alt="Screenshot 2020-09-30 at 21 37 03" src="https://user-images.githubusercontent.com/296665/94731504-2eff5e00-0365-11eb-8b79-7a6101143a8d.png">

Browser: Firefox 81
OS: MacOS 11 

Looks like the websocket connection fails and IPFS fails to start, causing `initialise` to fail entirely.

**Comment by icidasset** [comment]
Safari:

<img width="558" alt="Screenshot 2020-10-13 at 23 23 46" src="https://user-images.githubusercontent.com/296665/95917891-38e48080-0dab-11eb-9412-1987ca3ba3aa.png">

<img width="566" alt="Screenshot 2020-10-13 at 23 22 57" src="https://user-images.githubusercontent.com/296665/95917886-384bea00-0dab-11eb-8488-3a15b9d2f1ab.png">

**Comment by bmann** [comment]
I don’t think we should be including content from CDNs for stuff that is core to us. I don’t know if that is the issue, but that jumps out at me from the screenshot.

**Comment by icidasset** [comment]
@bmann Nah, nothing to do with the issue, the issue is with web sockets (which can identified by the `ws:// `wss://` protocols). But yeah, you're right, shouldn't rely on cdns (although we are caching it in case the cdn isn't available).

**Comment by icidasset** [comment]
Semi-related: The `ws` warnings/errors (note, not `wss`) should go away with the next libp2p release: https://github.com/ipfs/js-ipfs/issues/3298

**Comment by icidasset** [comment]
Ah, found related issues:
https://github.com/libp2p/js-libp2p/issues/312
https://github.com/ipfs/js-ipfs/issues/1837

**Comment by icidasset** [comment]
I'm thinking this fails in IPFS itself, because our gateway is on the bootstrap list.
Could also come from the `swarm.connect` which is done right after the IPFS setup.

I'm not sure we need that `swarm.connect` there 🤔 
I would think being in the bootstrap list automatically connects to that address.
Which is what I do on the lobby.

See https://github.com/fission-suite/webnative/blob/44d6a864c771f9d8b8f14acc408d239e67e428af/src/ipfs/config.ts#L51

Thoughts @dholms ?

**Comment by icidasset** [comment]
Wrote a reconnect script for this.
