### ISSUE TITLE
The docs/ link in the Readme is dead.

### ISSUE THREAD

**Issue by matheus23** [fission-suite/webnative#133]
> See [`docs/`](https://github.com/fission-suite/webnative/blob/master/docs) for more detailed documentation based on the source code.

I get a 404. Is this just outdated? Should it perhaps only link to the gitbook?

**Comment by icidasset** [comment]
Yeah, it's only in the npm distributions now. I'll remove the link for now and mention it's there in the node_modules dir. I looked for a way to browse npm packages online, but couldn't find anything that rendered the markdown properly (with working links and everything).

That said, we are going to move these docs to a website in the future.
