### ISSUE TITLE
Offer unsupported browser warning / error

### ISSUE THREAD

**Issue by walkah** [fission-suite/webnative#142]
# Summary

## Problem

Currently in Firefox Private mode and some versions of Brave, IndexedDB or other browser features are unavailable making webnative unusable.

### Impact

Attempting to redirect to auth lobby triggers and error.

## Solution

Have a state (probably a Scenario result from `wn.initialise()`?) that indicates the current browser is unsupported so developers can respond accordingly for their users.

**Comment by samuelandert** [comment]
I think I found another really weird edge case on this issue. When you open the auth.fission.codes or our app link in an in app ios browser windows popup, for example discord, linkedin or facebook... I think we have the same issue, that the key can not be stored in this special case and thus devices become unconnectable.
