### ISSUE TITLE
Show alert when leaving page while still updating DNSLink

### ISSUE THREAD

**Issue by icidasset** [fission-suite/webnative#146]
On by default, but devs should be able to disable this. Example scenario for disabling it: Quotes app saves a file named `history.json` each time you look at another quote. Reason for this being, the app shows a quote you haven't seen yet each time you click next. So reasons for not showing an alert: (1) Doesn't really matter much if history is lost, so the less we bother the user, the better. (2) History file is updated a lot, and a high chance this action is done right before closing the window, so we would probably be bothering the user quite a bit.

**Comment by expede** [comment]
Yeah, this is a good idea 👍 I saw this exact `alert` on unsynced close behaviour recently on iCloud.com (not to mention in native desktop apps)

**Comment by icidasset** [comment]
Alternatively, we could also do a push when coming back to the app. But this should probably not be done before we have conflict resolution.

**Comment by icidasset** [comment]
Implemented in #176

**Comment by icidasset** [comment]
Implemented in v0.22
