### ISSUE TITLE
Make webnative includable via a file path

### ISSUE THREAD

**Issue by matheus23** [fission-suite/webnative#168]
NB: Feature requests will only be considered if they solve a pain

# Summary

This in `package.json` doesn't work:
```json
{
  "dependencies": {
    "webnative": "../webnative"
  }
}
```

## Problem

When importing webnative like that, files `index.cjs.js`, `index.umd.js` and `index.es5.js` aren't in the right place after a `npm run build`.

This is not a problem with the npm version, since npm publish is run inside the `dist` directory. (See the justfile scripts).

### Impact

It's a little more difficult to develop for webnative.

## Solution

Two options:
1. Inform the user that they have to run `just build-and-clean` and include webnative via `../webnative/dist`, but I think this is unexpected and a little confusing
2. Change the package.json to refer to the `index.*.js` files as `dist/index.*.js` files and run `npm publish` from the root path (this breaks some users. E.g. in fission-suite/drive we'd need to change the build script to refer to a `webnative/dist/index.cjs.js` instead).

I assume we were publishing from within `dist` to not include any unwanted files. If we do option 2, we should include an [.npmignore](https://npm.github.io/publishing-pkgs-docs/publishing/the-npmignore-file.html) file.

:v:

**Comment by icidasset** [comment]
You shouldn't need to need to refer to `dist`, I think. Normally build tools refer to the `main`, `module` and `browser` fields in `package.json`, depending on the context. But yes, you still need to run `yarn build` to build webnative first.

Also the correct syntax is:
```json
{
  "dependencies": {
    "webnative": "file:../webnative"
  }
}
```

**Comment by matheus23** [comment]
Yeah right. The value for that in package.json at the moment is this:
https://github.com/fission-suite/webnative/blob/7a23b8329f660c1582d88116d33f04dfec41c639/package.json#L11

But there's no `index.cjs.js` at that path after a `yarn build`.
It works via npm, because the `package.json` file gets copied into `dist`. Then the path works out. Also the `npm publish` is run inside the `dist` folder instead of at the project root.

**Comment by icidasset** [comment]
Oh I see, yeah, that should be `dist` 👍 
And then we add the other stuff to the NPM ignore list.
We should indeed not copy the `package.json` into `dist`.
