### ISSUE TITLE
Add some feature detection and display to user

### ISSUE THREAD

**Issue by bmann** [fission-suite/webnative#172]
We had a report about issues on MacOS Mojave / Safari 12. 

This older browser is missing features that we rely on. 

Up to date versions of Chrome and Firefox do run on Mojave, so this is not a hard blocker. 

Resolution: we should be doing some level of feature detection and alerting the user that their current browser isn’t supported. 

Thanks @rosano

**Comment by icidasset** [comment]
We have feature detection already, I wonder what feature could be missing then?
Currently we check for indexedDB support and if the context is secure (HTTPS or localhost).

**Comment by icidasset** [comment]
Let me know if I'm missing anything, but feature detection is implemented.
