### ISSUE TITLE
Make `mkdir` automatic

### ISSUE THREAD

**Issue by rosano** [fission-suite/webnative#174]
The necessary parent directories could be created automatically when writing to any path without the developer needing to call `mkdir` or `exists`, eliminates this kind of thing:

```javascript
// via https://guide.fission.codes/developers/webnative#file-system
if (!await fs.exists(appPath)) {
  await fs.mkdir(appPath)
  await fs.publish()
}
```

**Comment by icidasset** [comment]
I think this was just a bad example in the docs and this should already work.
```js
fs.write("private/top/sub/file.md", "contents")
```
should work without having to create the `private/top/sub` directory.

Let me know if I'm wrong.
In any case, will adjust the documentation.

PS. The next version of the SDK `0.22`, will create the app data directories automatically.
