### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by icidasset** [fission-suite/webnative#237]
<img width="724" alt="Screenshot 2021-05-23 at 23 37 09" src="https://user-images.githubusercontent.com/296665/119277448-13143980-bc20-11eb-8b2d-75115de2ff03.png">
<img width="506" alt="Screenshot 2021-05-23 at 23 37 27" src="https://user-images.githubusercontent.com/296665/119277452-160f2a00-bc20-11eb-93d8-928cc905b464.png">

Got this while trying to use webnative using https://vitejs.dev/

```js
import * as webnative from "webnative"
```

PS: version 0.24.1 does work

**Comment by bgins** [comment]
I was able to reproduce this in a SvelteKit app that also relies on Vite.

Steps:

1. Follow the SvelteKit [getting started](https://kit.svelte.dev/docs#introduction-getting-started) steps
2. `npm install webnative`
3. Import webnative in `src/routes/__layout.svelte`

```svelte
<script>
	import * as webnative from "webnative";

	import Header from '$lib/Header/index.svelte';
	import '../app.css';
</script>
```

The error is similar, but not exactly the same as above:

![err](https://user-images.githubusercontent.com/7957636/119723006-d3b53b00-be21-11eb-914e-db3a86070a0a.png)

**Comment by bgins** [comment]
This seems similar: https://github.com/vitejs/vite/discussions/2344#discussioncomment-422731

Maybe it can addressed by configuring Vite appropriately.

**Comment by bgins** [comment]
Another discussion here: https://github.com/vitejs/vite/discussions/2278

**Comment by bgins** [comment]
More explanation, Vite will not shim node built-ins like `process`: https://github.com/vitejs/vite/issues/2723#issuecomment-808690781

**Comment by bgins** [comment]
Why?

```$ yarn why process
yarn why v1.22.10
[1/4] Why do we have the module "process"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "process@0.11.10"
info Reasons this module exists
   - "ipfs-core#ipfs-bitswap" depends on it
   - Hoisted from "ipfs-core#ipfs-bitswap#process"
info Disk size without dependencies: "36KB"
info Disk size with unique dependencies: "36KB"
info Disk size with transitive dependencies: "36KB"
info Number of shared dependencies: 0
Done in 1.19s.
```

js-ipfs

**Comment by icidasset** [comment]
I think `process` is not the only thing that's `undefined`.
When I "mock" (ie. use vite's `define` setting), I get the following error:
```
Uncaught ReferenceError: global is not defined
    at availableTypedArrays (index.js:20)
    at node_modules/.pnpm/which-typed-array@1.1.4/node_modules/which-typed-array/index.js (index.js:11)
    at __require (chunk-QF434IGH.js?v=90f5c12f:12)
    at node_modules/.pnpm/util@0.12.4/node_modules/util/support/types.js (types.js:8)
    at __require (chunk-QF434IGH.js?v=90f5c12f:12)
    at node_modules/.pnpm/util@0.12.4/node_modules/util/util.js (util.js:467)
    at __require (chunk-QF434IGH.js?v=90f5c12f:12)
    at node_modules/.pnpm/webnative@0.25.2/node_modules/webnative/dist/index.es5.js (index.ts:243)
    at __init (chunk-QF434IGH.js?v=90f5c12f:9)
    at dep:webnative:2
```

**Comment by jorishermans** [comment]
I had the same issue here as well ...
