### ISSUE TITLE
Default Ucan.isValid to check time bounds

### ISSUE THREAD

**Issue by expede** [fission-suite/webnative#240]
# Summary

## Problem

Validating a UCAN includes its time bounds. By default, we currently pass on expired tokens (as reported by Vera) in Discord.

Reported by @fuck-capitalism

## Solution

Accept a `checkTime` flag, defaulted to `true`

**Comment by expede** [comment]
Probably should move to `ts-ucan`

**Comment by icidasset** [comment]
Is done in https://github.com/ucan-wg/ts-ucan (including ts-ucan in webnative is WIP)
