### ISSUE TITLE
Ucan.build should fail if missing parameters

### ISSUE THREAD

**Issue by expede** [fission-suite/webnative#241]
# Summary

## Problem

Creating a UCAN without an `aud` field works fine, but fails to generate a valid UCAN.

Reported by @fuck-capitalism

### Impact

It's confusing for users!

## Solution

Fail with a helpful message when required fields are missing

**Comment by fuck-capitalism** [comment]
If audience is only required field, maybe just self sign if audience not present rather than failing

**Comment by icidasset** [comment]
The typescript types for this function mark `audience` and `issuer` both as required params. Is there like some kind of typescript compiler option that generates Javascript runtime errors automatically, for people who don't use Typescript 🤔

**Comment by expede** [comment]
@icidasset Yeah, we should definitely find something like that. Because WebNative is not required to run with TypeScript; it must also work well with plain ol' JavaScript.

**Comment by fuck-capitalism** [comment]
> The typescript types for this function mark `audience` and `issuer` both as required params.

It looks like only audience was required? see PR

**Comment by expede** [comment]
Likely should move to `ts-ucan`

**Comment by icidasset** [comment]
Is done in https://github.com/ucan-wg/ts-ucan (including ts-ucan in webnative is WIP)
New lib checks if both issuer and audience are DIDs.
