### ISSUE TITLE
Symlinks

### ISSUE THREAD

**Issue by expede** [fission-suite/webnative#246]
# Summary

## Problem

Merkle-DAGs link to specific nodes, which are always based on that specific file's contents. WNFS has named nodes that update based on a top-level mutable pointer.

### Impact

There is currently no way to point to the latest version of a file, or across file systems, in a way that WNFS itself understands. This forces users to roll their own for what should be an automatic operation

## Solution

Implement soft/symlinks

**Comment by walkah** [comment]
Dupe of #75 ?

**Comment by expede** [comment]
@walkah indeed it is!
