### ISSUE TITLE
Parse failure with webpack 4.x / create-react-app

### ISSUE THREAD

**Issue by walkah** [fission-suite/webnative#257]
# Summary

## Problem

Adding `webnative` to a create-react-app built app results in a parse error:

```
./node_modules/webnative/lib/fs/v1/PublicTree.js 157:49
Module parse failed: Unexpected token (157:49)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|       return { ...acc,
|         [cur.name]: { ...cur,
>           isFile: this.header.skeleton[cur.name]?.isFile
|         }
|       };
```

### Impact

It's too hard to get webpack integrated with a simple react app.

### Versions
- webnative v0.26.0
- create-react-app 4.0.3 (webpack 4.44)

**Comment by walkah** [comment]
This is specific to webnative v0.26- works fine in v0.25.2

**Comment by matheus23** [comment]
When I ran the blog repo against the PR, it fixed the issue, if I remember correctly.
Let me whether if fixed it for you, too :)
