### ISSUE TITLE
Webpack 5 module resolution errors

### ISSUE THREAD

**Issue by bgins** [fission-suite/webnative#265]
# Summary

## Problem

Building webnative 0.26.0 with webpack 5 fails with module resolution errors.

### Impact

It may be challenging to build with some webpack configs.

# Detail

**Describe the bug**

When building with webpack 5, two types of build errors occur
- Can't import from default-exporting module
- Module failed to resolve only because it was resolved as fully specified. 
 
Here are example outputs for each:

```
ERROR in ./node_modules/webnative/lib/common/base64.js 3:11-22
Can't import the named export 'Buffer'.'from' (imported as 'Buffer') from default-exporting module (only default export is available)
 @ ./node_modules/webnative/lib/auth.js 3:0-45 59:271-287
 @ ./node_modules/webnative/lib/index.js 130:0-26 130:0-26
 @ ./src/index.js 1:0-39 17:0-20 19:9-41 20:9-40 23:36-55 33:9-41 34:9-41 41:4-29 50:34-53 64:39-63 86:32-51 93:42-61 113:36-55 125:34-53 126:36-55

ERROR in ./node_modules/webnative/lib/crypto/browser.js 2:0-51
Module not found: Error: Can't resolve 'keystore-idb/rsa/index' in '/home/thuselem/development/work/fission/fission-stored-wasm-example/node_modules/webnative/lib/crypto'
Did you mean 'index.js'?
BREAKING CHANGE: The request 'keystore-idb/rsa/index' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
 @ ./node_modules/webnative/lib/setup/dependencies.js 1:0-54 5:16-36 8:17-38 9:17-38 10:19-42 11:20-44 14:16-39 17:16-43 20:23-52 21:24-54 22:17-40 23:14-34 24:23-52 25:23-52 26:19-44 27:16-38 28:15-36
 @ ./node_modules/webnative/lib/setup.js 28:0-58 28:0-58
 @ ./node_modules/webnative/lib/index.js 140:0-36 140:0-36
 @ ./src/index.js 1:0-39 17:0-20 19:9-41 20:9-40 23:36-55 33:9-41 34:9-41 41:4-29 50:34-53 64:39-63 86:32-51 93:42-61 113:36-55 125:34-53 126:36-55
```

**To Reproduce**
1. https://github.com/bgins/fission-stored-wasm-example uses webpack 5 with a simple configuration
2. Upgrade it to use `webnative` 0.26.0
3. `npm run build`

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Webnative version: 0.26.0

**Additional context**

This error does not occur in webnative 0.25.2.

**Comment by matheus23** [comment]
Took a deeper look at this. Seems like for this all to work, we need to add an exports map to `keystore-idb`. Otherwise only esbuild bundling will work (because it extends normal nodejs import semantics with typescript import semantics).

I've created an issue in keystore-idb to track this upgrade: https://github.com/fission-suite/keystore-idb/issues/46
