### ISSUE TITLE
Migration or file dump

### ISSUE THREAD

**Issue by expede** [fission-suite/webnative#300]
As part of the upgrade to WNFSv2, we need a lightweight way to let users keep their files. This can be either a migration script/app or decrypted dump. From conversations, the theory is that a dump to disk is the one with fewest edge cases and easiest to implement. However, @matheus23 has a quick & dirty migration script already from other work, which may be viable with a few changes.

**Comment by matheus23** [comment]
That repository is now public. You can already `npm install wnfs-migration`, and have `wnfs-migration` on your PATH, but it'll only migrate your filesystem into whatever currently is on the `aes-gcm-try-2` branch.

So, next things would be:
* Figure out & merge what PRs should be in the next filesystem version (e.g. we should probably pull in soft links at the same time)
* Test the migration tool with that filesystem version on staging with more than my machine
* Write some short docs about using the migration tool

**Comment by expede** [comment]
Waiting for NP publish on Webnative hard/soft links and AES-GCM compat

**Comment by expede** [comment]
@matheus23 please update the status

**Comment by matheus23** [comment]
This is done now.
* `wnfs-migration` is published on NPM: https://www.npmjs.com/package/wnfs-migration/v/2.0.0-alpha1 (as an alpha for now as long as the new WNFS hasn't been put on production).
* There are docs on how to run a migration: https://guide.fission.codes/accounts/account-signup/account-migration
* Brian and I tested the CLI more
