### ISSUE TITLE
links[Branch.Version] is undefined

### ISSUE THREAD

**Issue by bgins** [fission-suite/webnative#323]
# Summary

## Problem

Webnative throws an uncaught exception `TypeError: links[_pathJs.Branch.Version] is undefined`.

### Impact

This exception occurs with Vite, Parcel 2, and Webpack 5. Apps that use these bundlers/build tools will experience the exception.

## Solution

Not known. The exception appears to be thrown here: https://github.com/fission-suite/webnative/blob/8d405832892cb4cb8999269284ac55896cba9070/src/filesystem.ts#L100

# Detail

**Describe the bug**

Webnative throws an uncaught exception `TypeError: links[_pathJs.Branch.Version] is undefined`.

**To Reproduce**

 1.  Clone https://github.com/fission-suite/react-todomvc
 2. Upgrade webnative to `0.29.1` on the `vite`, `parcel`, and `webpack` branches
 3. `npm start` for local dev and `npm run build` for a build in each

**Expected behavior**

No errors in the console. The app works and can do TodoMVC things.

**Screenshots**

The `parcel` error:

<img width="954" alt="branch-version-error" src="https://user-images.githubusercontent.com/7957636/140582316-6d867909-d21e-40f1-b5f0-8c76c8cb1bc8.png">

The errors from the other bundlers are similar, but more difficult to read.

**Comment by matheus23** [comment]
Can you tell me what account this happened with?
The error would suggest that one of the top-level links (the version link at e.g. this account: https://matheus23.files.fission.name/) would be missing.
I'm not sure why that would be the case though :thinking: 

Was it a new account or an existing one?

**Comment by bgins** [comment]
It's an existing account: https://brian.files.fission.name/. And yeah, it does look like the `version` link is missing.

Not sure if it makes a difference, but I'm testing this with a local copy of `webnative` on the `matheus23/one-webcrypto-1-0-3` branch.
