### ISSUE TITLE
Use rejection sampling for AWAKE protocol

### ISSUE THREAD

**Issue by matheus23** [fission-suite/webnative#359]
Currently we generate the pin to be sent by generating 6 bytes and interpreting each modulo 10:
https://github.com/fission-suite/webnative/blob/d69fce99533b312ef94544fbec3f6db7542c9fdb/src/auth/linking/consumer.ts#L224-L226

This is most likely good enough, but has a slight bias towards digits 0-5. Instead, we should use rejection sampling to get a uniform distribution.

**Comment by expede** [comment]
Boas sampling works! The core problem that we're solving is the bias towards low numbers. There are multiple solutions (e.g. getting the digits from a `mod 10^6` random number). The actual choice of a solution up to implementer 👍
