### ISSUE TITLE
UX flows for AOL subdelegation

### ISSUE THREAD

**Issue by expede** [fission-suite/webnative#370]

**Comment by depatchedmode** [comment]
When you say "subdelegation" do you mean using the AOL I got from Application A to "login" to Application B?

**Comment by expede** [comment]
@depatchedmode this could have had WAY MORE info in it! 😅 

There are a couple scenarios, but essentially anywhere I want to give another app access to some but not all of my capabilities. At least in concept, this may or may not be the same application; maybe it's to a less trusted device.

As an example, as a Laconic Wallet user I may only want to give access to my Cosmos account (but not my LNT stuff) for the next week while I'm on my a borrowed iPad that has no password.

**Comment by depatchedmode** [comment]
Sweet. This helps clarify the scope. 

Moving to and from less trusted devices is a very rich set of flows to explore! Also, was not yet aware of diffuse.sh — checking it out now.

**Comment by avivash** [comment]
> Sweet. This helps clarify the scope.
> 
> Moving to and from less trusted devices is a very rich set of flows to explore! Also, was not yet aware of diffuse.sh — checking it out now.

built by @icidasset 🙌🏼

**Comment by depatchedmode** [comment]
The things that a person will be concerned about when sub-delegating:
+ **scope** of the delegation: what permissions am I granting
+ **identity** of the thing I'm delegating to: who exactly am I granting them to
+ **time** horizon of the delegation: how long are these permissions going to last?
+ **permanence**—how final is this decision? (eg. process for revocation)

I think WNFS' default folder structure, and practices about how it is used, is one of the most powerful first places to construct and improve sub-delegation UX.

**Comment by therealjeffg** [comment]
PDF export from the current state of the FigJAM

[App sub-delegation.pdf](https://github.com/fission-suite/webnative/files/8683809/App.sub-delegation.pdf)
