### ISSUE TITLE
Investigate what open source Rust for WNFS libraries

### ISSUE THREAD

**Issue by expede** [fission-suite/webnative#372]
Related to #309

e.g. https://github.com/ramfox/spiral_ratchet

**Comment by matheus23** [comment]
https://github.com/ipld/libipld

@appcypher I promised you a more precise explanation of what we need.
For WNFS v1 we'll need mostly `dag-pb`, for WNFS v2 we mostly need `dag-cbor`.
In both cases we just need some kind of builder where at the end there's a bunch of bytes coming out of these libraries.

If they're not wasmifyable yet, let's figure out what it would take to *make* them wasmifyable/extract a wasmifyable core and possibly contribute back (but that'd be a step 2!).

**Comment by matheus23** [comment]
Perhaps it's useful to show you how we're using the equivalent libraries in TS land today:

### WNFS v1 `dag-pb` usage

Encoding dag-pb nodes:
https://github.com/fission-suite/webnative/blob/500bbb70e76105176174be4e528f33bf06e0b4c8/src/ipfs/basic.ts#L77-L86

Decoding dag-pb nodes:
(somewhat hidden in here. js-ipfs actually does the heavy lifting of using dag-pb underneath here)
https://github.com/fission-suite/webnative/blob/500bbb70e76105176174be4e528f33bf06e0b4c8/src/ipfs/basic.ts#L67-L75

### WNFS v2 `dag-cbor` usage:
Encoding dag-cbor (some examples):
https://github.com/fission-suite/webnative/blob/e1eed4e750c668a6f54d9be701dc17e286b9eff4/src/fs/data/public/publicNode.ts#L430-L442

Decoding dag-cbor (one example):
https://github.com/fission-suite/webnative/blob/e1eed4e750c668a6f54d9be701dc17e286b9eff4/src/fs/data/public/publicNode.ts#L445-L453

**Comment by appcypher** [comment]
Thanks @matheus23. There are useful contexts.

**Comment by expede** [comment]
Closing!
