### ISSUE TITLE
Encrypt file's metadata with the header key not the parent key

### ISSUE THREAD

**Issue by dholms** [fission-suite/webnative#53]
## Problem
Currently metadata for a node is encrypted with that node's parent key (the key used to _encrypt that node_), not the node's own key (the key contained as a header value _in that node_). Thus, when a user is given access to a file, they don't get access to the metadata that goes with it

##
Encrypt metadata with the node's `ownKey` instead of the `parentKey`

**Comment by expede** [comment]
@icidasset I get the sense that this is actually fixed as part of the WNFS work done in between. Can you confirm?

**Comment by icidasset** [comment]
I'm not sure. If I'm reading the code correctly, `file.header.key` is the content key and `file.key` is the key used to encrypt the file itself? See below:

https://github.com/fission-suite/webnative/blob/2ac0e100484a73992a391c492c1c469b0794159c/src/fs/v1/PrivateFile.ts#L48-L64

**Comment by icidasset** [comment]
There doesn't seem to be any reference in the code to a parent key, so I guess it's fixed?
When creating a new file, a new key is generated here:
https://github.com/fission-suite/webnative/blob/2ac0e100484a73992a391c492c1c469b0794159c/src/fs/v1/PrivateTree.ts#L116-L117

**Comment by icidasset** [comment]
@dholms Can you confirm this is fixed, looks like it?

**Comment by dholms** [comment]
Yup yup this is fixed :+1:

**Comment by icidasset** [comment]
Nice, thx!
