### ISSUE TITLE
Serialize Filesystem as list before adding to IPFS

### ISSUE THREAD

**Issue by dholms** [fission-suite/webnative#56]
Right now the structure of FLOOFS in IPFS mimics its structure locally (tree). We should serialize the private filesystem into a list before adding to IPFS

Details here: https://talk.fission.codes/t/floofs-restructuring/718

**Comment by icidasset** [comment]
Do we still want to do this at some point?

**Comment by expede** [comment]
👀

**Comment by expede** [comment]
@icidasset no this Issue is super stale. The change is incompatible with file versioning.

**Comment by expede** [comment]
Thanks for pointing it out!!
