### ISSUE TITLE
Hard/soft links

### ISSUE THREAD

**Issue by icidasset** [fission-suite/webnative#75]
```haskell
hardLink :: Name -> VNode
softLink :: Name -> Maybe VNode
```
> This means that hard links are guaranteed to have some data at the pointer. Soft links may not, hence the Maybe.

**Comment by expede** [comment]
@walkah Soft-/symlinks are something that come up a LOT, and would be a very helpful addition to the SDK. They're mentioned in various parts of the whitepaper. You can think of them two ways: hard vs soft links (UNIX), or reference vs duplicate (macOS). Hard links are "merely" CIDs; soft links are more open to how exactly we structure them.

A hard link means that you're not going to get updates — it's _exactly_ this version of the file , which is exactly what you want aspart of the main spine of a file system. However, sometimes you want the same file referenced from multiple places without it actually being responsible for maintaining the version.

The downside of a symlink is that it's possible for something to not be at the reference.

# Use Cases

* [ ] Reference the _latest_ (moving) version referenced from multiple place in same user's FS
  * [ ] `/Private` -> `/Public` by name
  * [ ] `/Public` -> `/Private` by human-readable file path (not name filters), OR by hard link plus relative named path
* [ ] Reference the _latest_ (moving) version referenced across users FSes
* [ ] Point to mutable URIs (e.g. website, image, &c, though ingesting this data to IPFS even better)
* [ ] Re-use inside the `share_*` sections to point to MMPT locations (and a key to enter the private section at that point)

I realize that the above can be much further specified. In theory this is straightforwad, but the devil will be in the details. Let's chat before starting breaking ground on this ⚒️
