### ISSUE TITLE
Typescript error: 'from' expected TS1005

### ISSUE THREAD

**Issue by patdryburgh** [fission-suite/webnative#85]
# Summary

## Problem

I am in the process of switching out the old Fission Typescript client with the new webnative sdk in https://github.com/fission-suite/ipfs-photo-gallery/ and have run into a Typescript error:

```
/ipfs-photo-gallery/node_modules/webnative/index.d.ts
TypeScript error in /Users/patdryburgh/Development/ipfs-photo-gallery/node_modules/webnative/index.d.ts(49,10):
'from' expected.  TS1005

    47 | export * from './filesystem';
    48 | export declare const fs: typeof FileSystem;
  > 49 | export * as dataRoot from './data-root';
       |          ^
    50 | export * as did from './did';
    51 | export * as lobby from './lobby';
    52 | export * as setup from './setup';
```

### Impact

Not sure how to proceed until this error is fixed and not sure exactly what's causing it. I've created a PR in the IPFS Photo Gallery repo so you can see what I've done so far and suggest what I might be doing wrong. Happy to provide any other details you require :)

https://github.com/fission-suite/ipfs-photo-gallery/pull/20

**Comment by icidasset** [comment]
Hey Pat. This export syntax was added in [Typescript 3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html) and it looks like you're on `v3.7`.
Try upgrading and let me know if it works.

**Comment by patdryburgh** [comment]
Thanks, @icidasset! That worked :)
